# Site Settings
title:               "Abhinav Modi"
tagline:             "Masters in Robotics at the University of Maryland"
description:         "Abhinav Modi is a graduate student pursuing his Masters in Robotics at the University of Maryland. His research interests include mobile robotics, state estimation, computer vision and machine learning."
baseurl:             # /
url: 			           # http://leeclem.net
github:
  repo:              "https://github.com/abhi1625/abhinavmodi.github.io"
author:
  name:              "Abhinav Modi"
  email:             "abhi1625@umd.edu"
  twitter:           "leeclemne"
  instagram:
  github:            "abhi1625"
  facebook:
  linkedin:          "abhinavmodi16"
  scholar:           "skVilbAAAAAJ"
paginate:            15
paginate_path:       "/blog/page:num/"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           pretty
plugins:             [jekyll-paginate]

# Collections
collections:
  - projects
  - teaching
  - service
